// Package airflowv2 contains a typed HTTP client generated from the Apache
// Airflow REST API v2 OpenAPI specification (FastAPI-based, /api/v2).
//
// Files types.gen.go and client.gen.go are generated by oapi-codegen.
// Run `make generate` to refresh them after updating
// api/airflow-v2-openapi.yaml. See api/VERSION for the pinned Airflow
// release the spec was captured from.
package airflowv2

//go:generate go tool oapi-codegen -config ../../../../api/config-v2-types.yaml ../../../../api/airflow-v2-openapi.yaml
//go:generate go tool oapi-codegen -config ../../../../api/config-v2-client.yaml ../../../../api/airflow-v2-openapi.yaml
