// Package airflowv1 contains a typed HTTP client generated from the Apache
// Airflow REST API v1 OpenAPI specification (Connexion-based, /api/v1).
//
// Files types.gen.go and client.gen.go are generated by oapi-codegen.
// Run `make generate` to refresh them after updating
// api/airflow-v1-openapi.yaml. See api/VERSION for the pinned Airflow
// release the spec was captured from.
package airflowv1

//go:generate go tool oapi-codegen -config ../../../../api/config-v1-types.yaml ../../../../api/airflow-v1-openapi.yaml
//go:generate go tool oapi-codegen -config ../../../../api/config-v1-client.yaml ../../../../api/airflow-v1-openapi.yaml
